version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9000:9000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
